"""
Auto-generated Protocol interfaces for procedure implementations.

DO NOT EDIT THIS FILE MANUALLY.
Generated from procedures.d.yaml by dizzy.utils.generate_procedure_contexts
"""

from typing import Protocol
from gen.procedures import (
    AddTodoContext,
    CompleteTodoContext,
    DeleteTodoContext,
)

from gen.commands import (
    AddTodo,
    CompleteTodo,
    DeleteTodo,
)


class AddTodoProcedureProtocol(Protocol):
    """Protocol for AddTodo procedure implementations (add_todo)."""
    
    def __call__(self, context: AddTodoContext, command: AddTodo) -> None:
        """Execute the AddTodo procedure."""
        ...


class CompleteTodoProcedureProtocol(Protocol):
    """Protocol for CompleteTodo procedure implementations (complete_todo)."""
    
    def __call__(self, context: CompleteTodoContext, command: CompleteTodo) -> None:
        """Execute the CompleteTodo procedure."""
        ...


class DeleteTodoProcedureProtocol(Protocol):
    """Protocol for DeleteTodo procedure implementations (delete_todo)."""
    
    def __call__(self, context: DeleteTodoContext, command: DeleteTodo) -> None:
        """Execute the DeleteTodo procedure."""
        ...

