#!/usr/bin/env python3
"""
Generate Protocol interfaces and Context classes from feature definitions.

This script reads a feature YAML file (with procedures and policies) and generates
Python Protocol interfaces and Context dataclasses for command handlers.

Executes after generate_linkml_from_feature.py in the code generation pipeline.
"""

import argparse
import sys
from pathlib import Path
from typing import Dict, List

import yaml


def generate_context_for_procedure(
    proc_name: str,
    proc_def: Dict,
    output_path: Path,
    events_import_path: str = "gen.events.pyd",
):
    """Generate a single ProcedureContext class file with emit and query nested objects."""

    command_name = proc_def["command"]

    lines = [
        '"""',
        f"Auto-generated context for {proc_name} procedure.",
        "",
        "DO NOT EDIT THIS FILE MANUALLY.",
        "Generated from feature YAML by generate_protocols_from_commands.py",
        '"""',
        "",
        "from dataclasses import dataclass",
        "from typing import Callable",
        "",
    ]

    # Collect event types for this procedure
    event_types = set()
    if "emits" in proc_def:
        for event_name in proc_def["emits"]:
            event_types.add(event_name)

    if event_types:
        lines.append("# Import event types")
        lines.append(f"from {events_import_path} import (")
        for event_type in sorted(event_types):
            lines.append(f"    {event_type},")
        lines.append(")")
        lines.append("")

    lines.append("")

    # Generate Emitters class
    emitters_class = f"{command_name}_emitters"
    lines.append("@dataclass")
    lines.append(f"class {emitters_class}:")
    lines.append(f'    """Emitters for {command_name} procedure ({proc_name})."""')

    if "emits" in proc_def and proc_def["emits"]:
        for event_name in proc_def["emits"]:
            lines.append(f"    {event_name}: Callable[[{event_name}], None]")
    else:
        lines.append("    pass")

    lines.append("")
    lines.append("")

    # Generate Queries class
    queries_class = f"{command_name}_queries"
    lines.append("@dataclass")
    lines.append(f"class {queries_class}:")
    lines.append(f'    """Queries for {command_name} procedure ({proc_name})."""')
    lines.append("    pass")  # Placeholder for future query support

    lines.append("")
    lines.append("")

    # Generate Context class
    context_class = f"{command_name}_context"
    lines.append("@dataclass")
    lines.append(f"class {context_class}:")
    lines.append(f'    """Context for {command_name} procedure ({proc_name})."""')
    lines.append(f"    emit: {emitters_class}")
    lines.append(f"    query: {queries_class}")
    lines.append("")

    # Write to file
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w") as f:
        f.write("\n".join(lines))


def generate_context_classes(
    procedures: Dict,
    output_dir: Path,
    events_import_path: str = "gen.events.pyd",
):
    """Generate individual ProcedureContext class files."""

    contexts_dir = output_dir / "procedure" / "py"
    contexts_dir.mkdir(parents=True, exist_ok=True)

    # Create __init__.py files to make directories proper packages
    (output_dir / "procedure" / "__init__.py").touch()
    (contexts_dir / "__init__.py").touch()

    print(f"✓ Generating procedure contexts in {contexts_dir}")
    print(f"  Found {len(procedures)} procedures:")

    for proc_name, proc_def in procedures.items():
        command_name = proc_def["command"]
        output_path = contexts_dir / f"{proc_name}_context.py"
        generate_context_for_procedure(proc_name, proc_def, output_path, events_import_path)
        print(f"    - {output_path.name}")


def generate_protocol_for_procedure(
    proc_name: str,
    proc_def: Dict,
    output_path: Path,
    contexts_module_base: str,
    commands_import_path: str = "gen.commands.pyd",
):
    """Generate a single Protocol interface file for a procedure implementation."""

    command_name = proc_def["command"]
    protocol_name = f"{command_name}_procedure_protocol"
    description = proc_def.get("description", f"{command_name} procedure")

    lines = [
        '"""',
        f"Auto-generated Protocol interface for {proc_name} procedure.",
        "",
        "DO NOT EDIT THIS FILE MANUALLY.",
        "Generated from feature YAML by generate_protocols_from_commands.py",
        '"""',
        "",
        "from typing import Protocol",
        "",
        f"from .{proc_name}_context import {command_name}_context",
        f"from {commands_import_path} import {command_name}",
        "",
        "",
        f"class {protocol_name}(Protocol):",
        f'    """Protocol for {command_name} procedure implementations ({proc_name})."""',
        "",
        f"    def __call__(self, context: {command_name}_context, command: {command_name}) -> None:",
        f'        """',
        f"        Execute the {command_name} procedure.",
        f"        ",
        f"        {description}",
        f'        """',
        f"        ...",
        "",
    ]

    # Write to file
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w") as f:
        f.write("\n".join(lines))


def generate_procedure_protocols(
    procedures: Dict,
    output_dir: Path,
    contexts_module_base: str,
    commands_import_path: str = "gen.commands.pyd",
):
    """Generate individual Protocol interface files for procedure implementations."""

    protocols_dir = output_dir / "procedure" / "py"
    protocols_dir.mkdir(parents=True, exist_ok=True)

    print(f"✓ Generating procedure protocols in {protocols_dir}")
    print(f"  Found {len(procedures)} procedure protocols:")

    for proc_name, proc_def in procedures.items():
        output_path = protocols_dir / f"{proc_name}_protocol.py"
        generate_protocol_for_procedure(
            proc_name, proc_def, output_path, contexts_module_base, commands_import_path
        )
        print(f"    - {output_path.name}")


def generate_protocol_for_policy(
    policy_name: str,
    policy_def: Dict,
    output_path: Path,
    commands_import_path: str = "gen.commands.pyd",
    events_import_path: str = "gen.events.pyd",
):
    """Generate a single Protocol interface file for a policy implementation."""

    protocol_name = f"{policy_name}_policy_protocol"
    description = policy_def.get("description", f"{policy_name} policy")

    lines = [
        '"""',
        f"Auto-generated Protocol interface for {policy_name} policy.",
        "",
        "DO NOT EDIT THIS FILE MANUALLY.",
        "Generated from feature YAML by generate_protocols_from_commands.py",
        '"""',
        "",
        "from typing import Protocol, List",
        "",
    ]

    # Collect command and event types for this policy
    command_types = set()
    event_types = set()
    if "emits" in policy_def:
        for item in policy_def["emits"]:
            command_types.add(item)
    if "event" in policy_def:
        event_types.add(policy_def["event"])

    # Import command types if any
    if command_types:
        lines.append(f"from {commands_import_path} import (")
        for command_name in sorted(command_types):
            lines.append(f"    {command_name},")
        lines.append(")")
        lines.append("")

    # Import event types if any
    if event_types:
        lines.append(f"from {events_import_path} import (")
        for event_name in sorted(event_types):
            lines.append(f"    {event_name},")
        lines.append(")")
        lines.append("")

    lines.append("")

    # Determine the input type (event-based policy)
    if "event" in policy_def:
        input_type = policy_def["event"]
        input_param = "event"
    else:
        # Skip policies without clear input
        return

    # Determine return type based on what the policy emits
    if "emits" in policy_def and policy_def["emits"]:
        # Policy returns list of commands to emit
        emitted_types = [item for item in policy_def["emits"]]
        # For simplicity, use List of first type (could be Union for mixed types)
        return_type = f"List[{emitted_types[0]}]"
    else:
        # Policy just validates (returns bool)
        return_type = "bool"

    lines.append(f"class {protocol_name}(Protocol):")
    lines.append(
        f'    """Protocol for {policy_name} policy implementations ({policy_name})."""'
    )
    lines.append("")
    lines.append(f"    def __call__(self, {input_param}: {input_type}) -> {return_type}:")
    lines.append(f'        """')
    lines.append(f"        Evaluate the {policy_name} policy.")
    lines.append(f"        ")
    lines.append(f"        {description}")
    lines.append(f'        """')
    lines.append(f"        ...")
    lines.append("")

    # Write to file
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w") as f:
        f.write("\n".join(lines))


def generate_policy_protocols(
    policies: Dict,
    output_dir: Path,
    commands_import_path: str = "gen.commands.pyd",
    events_import_path: str = "gen.events.pyd",
):
    """Generate individual Protocol interface files for policy implementations."""

    policies_dir = output_dir / "policy" / "py"
    policies_dir.mkdir(parents=True, exist_ok=True)

    # Create __init__.py files to make directories proper packages
    (output_dir / "policy" / "__init__.py").touch()
    (policies_dir / "__init__.py").touch()

    print(f"✓ Generating policy protocols in {policies_dir}")
    print(f"  Found {len(policies)} policy protocols:")

    for policy_name, policy_def in policies.items():
        output_path = policies_dir / f"{policy_name}_protocol.py"
        generate_protocol_for_policy(
            policy_name, policy_def, output_path, commands_import_path, events_import_path
        )
        print(f"    - {output_path.name}")


def main():
    parser = argparse.ArgumentParser(
        description="Generate Protocol interfaces and Context classes from feature YAML"
    )
    parser.add_argument(
        "feature_file", help="Path to feature YAML file (*.feat.yaml)"
    )
    parser.add_argument(
        "output_dir", help="Directory to write generated protocol files"
    )
    parser.add_argument(
        "--events-import",
        default="gen.events.pyd",
        help="Python import path for generated event models (default: gen.events.pyd)",
    )
    parser.add_argument(
        "--commands-import",
        default="gen.commands.pyd",
        help="Python import path for generated command models (default: gen.commands.pyd)",
    )
    parser.add_argument(
        "--contexts-import",
        help="Python import path for generated context classes (default: derived from output_dir)",
    )

    args = parser.parse_args()

    feature_path = Path(args.feature_file)
    output_dir = Path(args.output_dir)

    if not feature_path.exists():
        print(f"Error: Feature file {feature_path} does not exist")
        sys.exit(1)

    # Load the feature YAML
    print(f"Loading feature from {feature_path}...")
    with open(feature_path) as f:
        feature_data = yaml.safe_load(f)

    # Determine contexts module base path for imports
    if args.contexts_import:
        contexts_module_base = args.contexts_import
    else:
        # Derive from output directory structure
        # e.g., app/dedupe/scan_and_upload/gen -> dedupe.scan_and_upload.gen.procedure.py
        contexts_module_base = str(output_dir).replace("/", ".").lstrip(".")
        if contexts_module_base.startswith("app."):
            contexts_module_base = contexts_module_base[4:]  # Remove 'app.' prefix
        contexts_module_base += ".procedure.py"

    # Generate procedure contexts and protocols if procedures are defined
    procedures = feature_data.get("procedures", {})
    if procedures:
        print(f"\nGenerating procedure contexts and protocols...")

        generate_context_classes(
            procedures,
            output_dir,
            args.events_import,
        )

        generate_procedure_protocols(
            procedures,
            output_dir,
            contexts_module_base,
            args.commands_import,
        )
    else:
        print("\nNo procedures found in feature")

    # Generate policy protocols if policies are defined
    policies = feature_data.get("policies", {})
    if policies:
        print(f"\nGenerating policy protocols...")

        generate_policy_protocols(
            policies, output_dir, args.commands_import, args.events_import
        )
    else:
        print("\nNo policies found in feature")

    print("\n✓ Done!")


if __name__ == "__main__":
    main()
