"""
Auto-generated Protocol interfaces for query implementations.

DO NOT EDIT THIS FILE MANUALLY.
Generated from queries.yaml by dizzy.utils.generate_query_interfaces
"""

from typing import Protocol
from gen.queries import (
    ListHardDrivesInput,
    ListHardDrives,
    ListPartitionsInput,
    ListPartitions,
    ListFileItemsInput,
    ListFileItems,
    GetAllEventsInput,
    GetAllEvents,
    GetEventsByTypesInput,
    GetEventsByTypes,
    PutContentInput,
    PutContent,
    GetContentInput,
    GetContent,
    CheckExistsInput,
    CheckExists,
)


class ListHardDrivesProtocol(Protocol):
    """Protocol for ListHardDrives query implementations."""
    
    def execute(self, query_input: ListHardDrivesInput) -> ListHardDrives:
        """Execute the ListHardDrives query."""
        ...


class ListPartitionsProtocol(Protocol):
    """Protocol for ListPartitions query implementations."""
    
    def execute(self, query_input: ListPartitionsInput) -> ListPartitions:
        """Execute the ListPartitions query."""
        ...


class ListFileItemsProtocol(Protocol):
    """Protocol for ListFileItems query implementations."""
    
    def execute(self, query_input: ListFileItemsInput) -> ListFileItems:
        """Execute the ListFileItems query."""
        ...


class GetAllEventsProtocol(Protocol):
    """Protocol for GetAllEvents query implementations."""
    
    def execute(self, query_input: GetAllEventsInput) -> GetAllEvents:
        """Execute the GetAllEvents query."""
        ...


class GetEventsByTypesProtocol(Protocol):
    """Protocol for GetEventsByTypes query implementations."""
    
    def execute(self, query_input: GetEventsByTypesInput) -> GetEventsByTypes:
        """Execute the GetEventsByTypes query."""
        ...


class PutContentProtocol(Protocol):
    """Protocol for PutContent query implementations."""
    
    def execute(self, query_input: PutContentInput) -> PutContent:
        """Execute the PutContent query."""
        ...


class GetContentProtocol(Protocol):
    """Protocol for GetContent query implementations."""
    
    def execute(self, query_input: GetContentInput) -> GetContent:
        """Execute the GetContent query."""
        ...


class CheckExistsProtocol(Protocol):
    """Protocol for CheckExists query implementations."""
    
    def execute(self, query_input: CheckExistsInput) -> CheckExists:
        """Execute the CheckExists query."""
        ...

