# Run a batch to completion, emitting PROV relationship facts as it goes.
#
# For each recipe step we emit step_performed (prov:Activity / wasAssociatedWith)
# and entity_consumed (prov:used) for that step's ingredient inputs. If the recipe
# requires an upstream entity, we consume the available lot and, after producing the
# output, emit entity_derived (prov:wasDerivedFrom) to link output -> source. The
# terminal entity_produced (prov:wasGeneratedBy) is the signal the cascade policy
# listens for; batch_completed closes the batch.
#
# A run that cannot proceed because its required lot is gone (another batch consumed
# it first) emits batch_run_failed and stops *before* any other event — failures are
# facts, not exceptions, so a cascade never aborts and never leaves partial state.
from datetime import datetime, timezone
from decimal import Decimal

from gen_int.python.procedure.run_batch_context import run_batch_context
from gen_def.pydantic.commands import AdvanceBatch
from gen_def.pydantic.events import (
    StepPerformed,
    EntityConsumed,
    EntityProduced,
    EntityDerived,
    BatchCompleted,
    BatchRunFailed,
)
from gen_def.pydantic.query.get_batch import GetBatchInput
from gen_def.pydantic.query.get_recipe import GetRecipeInput
from gen_def.pydantic.query.get_recipe_steps import GetRecipeStepsInput
from gen_def.pydantic.query.get_step_inputs import GetStepInputsInput
from gen_def.pydantic.query.check_inventory import CheckInventoryInput


def run_batch(
    context: run_batch_context,
    command: AdvanceBatch,
) -> None:
    batch_id = command.batch_id

    batch = context.query.get_batch(GetBatchInput(batch_id=batch_id))
    if batch.recipe_id is None:
        raise ValueError(f"unknown batch: {batch_id}")
    recipe_id = batch.recipe_id

    recipe = context.query.get_recipe(GetRecipeInput(recipe_id=recipe_id))
    steps = context.query.get_recipe_steps(GetRecipeStepsInput(recipe_id=recipe_id))
    inputs = context.query.get_step_inputs(GetStepInputsInput(recipe_id=recipe_id))

    if not steps.step_orders:
        raise ValueError(f"recipe {recipe_id} has no steps to run")

    now = datetime.now(timezone.utc)

    # Resolve the upstream dependency up front. If it is not actually available — a
    # lot existed when this batch opened but another batch consumed it since — record
    # the failure as a fact and stop, before emitting any step or production events.
    source_entity_id: str | None = None
    requires = (recipe.requires_type or "").strip()
    if requires:
        upstream = context.query.check_inventory(CheckInventoryInput(entity_type=requires))
        if not upstream.available or upstream.entity_id is None:
            context.emit.batch_run_failed(
                BatchRunFailed(
                    batch_id=batch_id,
                    reason=f"no available {requires} to consume",
                    failed_at=now,
                )
            )
            return
        source_entity_id = upstream.entity_id

    # Perform each step as a PROV activity, consuming its ingredient inputs.
    activity_by_step: dict[int, str] = {}
    for i, step_order in enumerate(steps.step_orders):
        activity_id = f"{batch_id}:step{step_order}"
        activity_by_step[step_order] = activity_id
        tool = steps.tool_ids[i] if i < len(steps.tool_ids) else ""
        context.emit.step_performed(
            StepPerformed(
                activity_id=activity_id,
                batch_id=batch_id,
                step_order=step_order,
                activity_kind=steps.activity_kinds[i],
                tool_id=(tool or None),
                performed_at=now,
            )
        )
        for j, in_step in enumerate(inputs.step_orders):
            if in_step == step_order:
                ingredient = inputs.ingredient_types[j]
                context.emit.entity_consumed(
                    EntityConsumed(
                        activity_id=activity_id,
                        entity_id=f"pantry:{ingredient}",
                        entity_type=ingredient,
                        role="ingredient",
                    )
                )

    # The output is generated by the final step's activity.
    final_step = steps.step_orders[-1]
    final_activity = activity_by_step[final_step]

    # Consume the upstream chained dependency (prov:used), if any.
    if source_entity_id is not None:
        context.emit.entity_consumed(
            EntityConsumed(
                activity_id=final_activity,
                entity_id=source_entity_id,
                entity_type=requires,
                role="upstream",
            )
        )

    # Produce the output entity (prov:wasGeneratedBy) — the cascade trigger.
    output_entity_id = f"{batch_id}:{recipe.output_type}"
    context.emit.entity_produced(
        EntityProduced(
            entity_id=output_entity_id,
            activity_id=final_activity,
            batch_id=batch_id,
            entity_type=recipe.output_type,
            qty=Decimal(1),
            unit=recipe.output_unit,
            produced_at=now,
        )
    )

    # Record the derivation edge (prov:wasDerivedFrom).
    if source_entity_id is not None:
        context.emit.entity_derived(
            EntityDerived(
                output_entity_id=output_entity_id,
                source_entity_id=source_entity_id,
            )
        )

    context.emit.batch_completed(BatchCompleted(batch_id=batch_id, completed_at=now))
