"""
Auto-generated Protocol interfaces for policy implementations.

DO NOT EDIT THIS FILE MANUALLY.
Generated from policies.d.yaml by dizzy.utils.generate_policy_contexts
"""

from typing import Protocol
from gen.policies import (
    PartitionMountAssignedPolicyContext,
)

from gen.events import (
    PartitionMountAssigned,
)


class PartitionMountAssignedPolicyProtocol(Protocol):
    """Protocol for PartitionMountAssigned policy implementations (partition_mount_reconciler)."""
    
    def __call__(self, context: PartitionMountAssignedPolicyContext, event: PartitionMountAssigned) -> None:
        """Execute the PartitionMountAssigned policy."""
        ...

