#!/usr/bin/env python3

"""
Generate Protocol interface classes from LinkML query definitions.

This utility reads a queries.yaml file and generates Protocol classes that define
the interface for query implementations. This allows multiple implementations
(Linux, Windows, different backends) to be type-checked against the same schema.
"""

import yaml
from pathlib import Path
from typing import Dict, List, Tuple


def parse_queries_yaml(yaml_path: Path) -> Dict:
    with open(yaml_path) as f:
        return yaml.safe_load(f)


def find_query_pairs(schema: Dict) -> List[Tuple[str, str]]:
    """Find pairs of Input/Output query classes."""
    classes = schema.get('classes', {})
    pairs = []

    for class_name in classes:
        if class_name.endswith('Input'):
            # Find corresponding output class (remove 'Input' suffix)
            output_name = class_name[:-5]  # Remove 'Input'
            if output_name in classes:
                pairs.append((class_name, output_name))

    return pairs


def generate_query_interfaces(
    queries_yaml: Path,
    output_file: Path,
    gen_import_path: str = 'gen.queries'
):
    """
    Generate Protocol interface file from queries schema.

    Args:
        queries_yaml: Path to queries.yaml schema file
        output_file: Path where interfaces.py should be written
        gen_import_path: Python import path for generated Pydantic models
    """
    schema = parse_queries_yaml(queries_yaml)
    pairs = find_query_pairs(schema)

    lines = [
        '"""',
        'Auto-generated Protocol interfaces for query implementations.',
        '',
        'DO NOT EDIT THIS FILE MANUALLY.',
        f'Generated from {queries_yaml.name} by dizzy.utils.generate_query_interfaces',
        '"""',
        '',
        'from typing import Protocol',
        f'from {gen_import_path} import (',
    ]

    # Import all Input and Output classes
    for input_class, output_class in pairs:
        lines.append(f'    {input_class},')
        lines.append(f'    {output_class},')

    lines.append(')')
    lines.append('')
    lines.append('')

    # Generate Protocol for each query pair
    for input_class, output_class in pairs:
        protocol_name = f'{output_class}Protocol'
        lines.append(f'class {protocol_name}(Protocol):')
        lines.append(f'    """Protocol for {output_class} query implementations."""')
        lines.append(f'    ')
        lines.append(f'    def execute(self, query_input: {input_class}) -> {output_class}:')
        lines.append(f'        """Execute the {output_class} query."""')
        lines.append(f'        ...')
        lines.append('')
        lines.append('')

    # Write to file
    output_file.parent.mkdir(parents=True, exist_ok=True)
    with open(output_file, 'w') as f:
        f.write('\n'.join(lines))

    print(f"Generated protocol interfaces: {output_file}")
    print(f"Found {len(pairs)} query pairs:")
    for input_class, output_class in pairs:
        print(f"  - {input_class} -> {output_class}")


def main():
    """CLI entry point when run as script."""
    import sys

    if len(sys.argv) < 3:
        print("Usage: python -m dizzy.utils.generate_query_interfaces <queries.yaml> <output.py> [import_path]")
        sys.exit(1)

    queries_yaml = Path(sys.argv[1])
    output_file = Path(sys.argv[2])
    gen_import_path = sys.argv[3] if len(sys.argv) > 3 else 'gen.queries'

    generate_query_interfaces(queries_yaml, output_file, gen_import_path)


if __name__ == '__main__':
    main()
