#!/usr/bin/env python3

"""
Generate PolicyContext classes from policies.d.yaml.

This utility reads the policy definitions and generates Python dataclasses
for policy contexts with nested command emitters, queries, and mutators.

Policies consume Events and emit Commands (opposite of Procedures).
"""

import yaml
from pathlib import Path
from typing import Dict


def parse_policies_yaml(yaml_path: Path) -> Dict:
    with open(yaml_path) as f:
        return yaml.safe_load(f)


def generate_context_classes(
    policies: Dict,
    output_path: Path,
    events_import_path: str = 'gen.events',
    commands_import_path: str = 'gen.commands',
    queries_import_path: str = 'gen.queries',
    mutations_import_path: str = 'gen.mutations'
):
    """Generate PolicyContext classes."""

    lines = [
        '"""',
        'Auto-generated PolicyContext classes.',
        '',
        'DO NOT EDIT THIS FILE MANUALLY.',
        'Generated from policies.d.yaml by dizzy.utils.generate_policy_contexts',
        '"""',
        '',
        'from dataclasses import dataclass',
        'from typing import Callable',
        '',
    ]

    # Import event types
    lines.append('# Import event types')
    lines.append(f'from {events_import_path} import (')
    event_types = set()
    for policy_name in policies:
        # Policy name matches the event it handles
        event_types.add(policy_name)
    for event_type in sorted(event_types):
        lines.append(f'    {event_type},')
    lines.append(')')
    lines.append('')

    # Import command types
    lines.append('# Import command types')
    lines.append(f'from {commands_import_path} import (')
    command_types = set()
    for policy_name, policy_def in policies.items():
        if 'emitters' in policy_def:
            for command_type in policy_def['emitters'].values():
                command_types.add(command_type)
    for command_type in sorted(command_types):
        lines.append(f'    {command_type},')
    lines.append(')')
    lines.append('')

    # Import query types
    lines.append('# Import query types')
    lines.append(f'from {queries_import_path} import (')
    query_types = set()
    for policy_name, policy_def in policies.items():
        if 'queries' in policy_def:
            for query_type in policy_def['queries'].values():
                query_types.add(query_type)
                query_types.add(f'{query_type}Input')
    for query_type in sorted(query_types):
        lines.append(f'    {query_type},')
    lines.append(')')
    lines.append('')

    # Import mutation types
    lines.append('# Import mutation types')
    lines.append(f'from {mutations_import_path} import (')
    mutation_types = set()
    for policy_name, policy_def in policies.items():
        if 'mutators' in policy_def:
            for mutation_type in policy_def['mutators'].values():
                mutation_types.add(mutation_type)
                mutation_types.add(f'{mutation_type}Input')
    for mutation_type in sorted(mutation_types):
        lines.append(f'    {mutation_type},')
    lines.append(')')
    lines.append('')
    lines.append('')

    # Generate classes for each policy
    for policy_name, policy_def in policies.items():
        # Generate Emitters class (for Commands)
        emitters_class = f'{policy_name}PolicyEmitters'
        lines.append(f'@dataclass')
        lines.append(f'class {emitters_class}:')
        lines.append(f'    """Command emitters for {policy_name} policy."""')

        if 'emitters' in policy_def and policy_def['emitters']:
            for emit_name, command_type in policy_def['emitters'].items():
                # Remove 'emit_' prefix if present
                attr_name = emit_name.replace('emit_', '')
                lines.append(f'    {attr_name}: Callable[[{command_type}], None]')
        else:
            lines.append('    pass')

        lines.append('')
        lines.append('')

        # Generate Queries class
        queries_class = f'{policy_name}PolicyQueries'
        lines.append(f'@dataclass')
        lines.append(f'class {queries_class}:')
        lines.append(f'    """Queries for {policy_name} policy."""')

        if 'queries' in policy_def and policy_def['queries']:
            for query_name, query_type in policy_def['queries'].items():
                lines.append(f'    {query_name}: Callable[[{query_type}Input], {query_type}]')
        else:
            lines.append('    pass')

        lines.append('')
        lines.append('')

        # Generate Mutators class
        mutators_class = f'{policy_name}PolicyMutators'
        lines.append(f'@dataclass')
        lines.append(f'class {mutators_class}:')
        lines.append(f'    """Mutators for {policy_name} policy."""')

        if 'mutators' in policy_def and policy_def['mutators']:
            for mutator_name, mutation_type in policy_def['mutators'].items():
                lines.append(f'    {mutator_name}: Callable[[{mutation_type}Input], {mutation_type}]')
        else:
            lines.append('    pass')

        lines.append('')
        lines.append('')

        # Generate Context class
        context_class = f'{policy_name}PolicyContext'
        lines.append(f'@dataclass')
        lines.append(f'class {context_class}:')
        lines.append(f'    """Context for {policy_name} policy."""')
        lines.append(f'    emit: {emitters_class}')
        lines.append(f'    query: {queries_class}')
        lines.append(f'    mutate: {mutators_class}')
        lines.append('')
        lines.append('')

    # Write to file
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w') as f:
        f.write('\n'.join(lines))

    print(f"Generated policy contexts: {output_path}")
    print(f"Found {len(policies)} policies:")
    for policy_name in policies:
        print(f"  - {policy_name}PolicyContext")


def generate_protocol_interfaces(
    policies: Dict,
    output_path: Path,
    policies_import_path: str = 'gen.policies',
    events_import_path: str = 'gen.events'
):
    """Generate Protocol interfaces for policies."""

    lines = [
        '"""',
        'Auto-generated Protocol interfaces for policy implementations.',
        '',
        'DO NOT EDIT THIS FILE MANUALLY.',
        'Generated from policies.d.yaml by dizzy.utils.generate_policy_contexts',
        '"""',
        '',
        'from typing import Protocol',
        f'from {policies_import_path} import (',
    ]

    # Import all context classes
    imports = []
    for policy_name in policies:
        imports.append(f'    {policy_name}PolicyContext,')

    lines.extend(imports)
    lines.append(')')
    lines.append('')

    # Import event types
    lines.append(f'from {events_import_path} import (')
    for policy_name in policies:
        lines.append(f'    {policy_name},')
    lines.append(')')
    lines.append('')
    lines.append('')

    # Generate Protocol for each policy
    for policy_name in policies:
        protocol_name = f'{policy_name}PolicyProtocol'
        lines.append(f'class {protocol_name}(Protocol):')
        lines.append(f'    """Protocol for {policy_name} policy implementations."""')
        lines.append(f'    ')
        lines.append(f'    def __call__(self, context: {policy_name}PolicyContext, event: {policy_name}) -> None:')
        lines.append(f'        """Execute the {policy_name} policy."""')
        lines.append(f'        ...')
        lines.append('')
        lines.append('')

    # Write to file
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w') as f:
        f.write('\n'.join(lines))

    print(f"Generated policy protocols: {output_path}")
    print(f"Found {len(policies)} policy protocols:")
    for policy_name in policies:
        print(f"  - {policy_name}PolicyProtocol")


def generate_policy_contexts(
    policies_yaml: Path,
    contexts_file: Path,
    protocols_file: Path,
    events_import_path: str = 'gen.events',
    commands_import_path: str = 'gen.commands',
    queries_import_path: str = 'gen.queries',
    mutations_import_path: str = 'gen.mutations',
    policies_import_path: str = 'gen.policies'
):
    """
    Generate policy context classes and protocol interfaces.

    Args:
        policies_yaml: Path to policies.d.yaml schema file
        contexts_file: Path where policy context classes should be written
        protocols_file: Path where policy protocol interfaces should be written
        events_import_path: Python import path for generated event models
        commands_import_path: Python import path for generated command models
        queries_import_path: Python import path for generated query models
        mutations_import_path: Python import path for generated mutation models
        policies_import_path: Python import path for generated policy contexts
    """
    data = parse_policies_yaml(policies_yaml)
    policies = data.get('policies', {})

    generate_context_classes(
        policies,
        contexts_file,
        events_import_path,
        commands_import_path,
        queries_import_path,
        mutations_import_path
    )

    generate_protocol_interfaces(
        policies,
        protocols_file,
        policies_import_path,
        events_import_path
    )


def main():
    """CLI entry point when run as script."""
    import sys

    if len(sys.argv) < 4:
        print("Usage: python -m dizzy.utils.generate_policy_contexts <policies.yaml> <contexts.py> <protocols.py>")
        sys.exit(1)

    policies_yaml = Path(sys.argv[1])
    contexts_file = Path(sys.argv[2])
    protocols_file = Path(sys.argv[3])

    generate_policy_contexts(
        policies_yaml,
        contexts_file,
        protocols_file
    )


if __name__ == '__main__':
    main()
