"""
Auto-generated Protocol interfaces for query implementations.

DO NOT EDIT THIS FILE MANUALLY.
Generated from queries.yaml by dizzy.utils.generate_query_interfaces
"""

from typing import Protocol
from todo.gen.queries import (
    ListTodosInput,
    ListTodos,
    GetTodoInput,
    GetTodo,
)


class ListTodosProtocol(Protocol):
    """Protocol for ListTodos query implementations."""
    
    def execute(self, query_input: ListTodosInput) -> ListTodos:
        """Execute the ListTodos query."""
        ...


class GetTodoProtocol(Protocol):
    """Protocol for GetTodo query implementations."""
    
    def execute(self, query_input: GetTodoInput) -> GetTodo:
        """Execute the GetTodo query."""
        ...

