# Dedupe project automation

default:
    @just --list

gen:
    gen-pydantic def/models.yaml > gen/models.py
    gen-pydantic def/commands.yaml > gen/commands.py
    gen-pydantic def/queries.yaml > gen/queries.py
    gen-pydantic def/events.yaml > gen/events.py
    gen-pydantic def/mutations.yaml > gen/mutations.py
    
    python3 -m utils.generate_query_interfaces
    python3 -m utils.generate_mutation_interfaces


check:
    uv run ty check queries/

test:
    uv run pytest tests/

