# Dedupe project automation

default:
    @just --list

gen:
    gen-python def/models.yml > gen/models.py
    gen-python def/commands.yml > gen/commands.py
    gen-python def/queries.yml > gen/queries.py
    gen-python def/events.yml > gen/events.py
    gen-python def/mutations.yml > gen/mutations.py
    python3 -m utils.generate_query_interfaces
    python3 -m utils.generate_mutation_interfaces

check:
    uv run ty check queries/

test:
    uv run pytest tests/

