"""
Auto-generated Protocol interfaces for procedure implementations.

DO NOT EDIT THIS FILE MANUALLY.
Generated from procedures.d.yaml by dizzy.utils.generate_procedure_contexts
"""

from typing import Protocol
from gen.procedures import (
    InspectStorageContext,
    ScanPartitionContext,
    AssignPartitionMountContext,
)

from gen.commands import (
    AssignPartitionMount,
    InspectStorage,
    ScanPartition,
)


class InspectStorageProcedureProtocol(Protocol):
    """Protocol for InspectStorage procedure implementations (storage_inspector)."""
    
    def __call__(self, context: InspectStorageContext, command: InspectStorage) -> None:
        """Execute the InspectStorage procedure."""
        ...


class ScanPartitionProcedureProtocol(Protocol):
    """Protocol for ScanPartition procedure implementations (partition_scanner)."""
    
    def __call__(self, context: ScanPartitionContext, command: ScanPartition) -> None:
        """Execute the ScanPartition procedure."""
        ...


class AssignPartitionMountProcedureProtocol(Protocol):
    """Protocol for AssignPartitionMount procedure implementations (partition_mount_assigner)."""
    
    def __call__(self, context: AssignPartitionMountContext, command: AssignPartitionMount) -> None:
        """Execute the AssignPartitionMount procedure."""
        ...

