#!/usr/bin/env python3

"""
Generate Protocol interface classes from LinkML query definitions.

This utility reads def/queries.yaml and generates Protocol classes that define
the interface for query implementations. This allows multiple implementations
(Linux, Windows, different backends) to be type-checked against the same schema.
"""

import yaml
from pathlib import Path
from typing import Dict, List, Tuple


def parse_queries_yaml(yaml_path: Path) -> Dict:
    with open(yaml_path) as f:
        return yaml.safe_load(f)


def find_query_pairs(schema: Dict) -> List[Tuple[str, str]]:
    """Find pairs of Input/Output query classes."""
    classes = schema.get('classes', {})
    pairs = []

    for class_name in classes:
        if class_name.endswith('Input'):
            # Find corresponding output class (remove 'Input' suffix)
            output_name = class_name[:-5]  # Remove 'Input'
            if output_name in classes:
                pairs.append((class_name, output_name))

    return pairs


def generate_protocol_file(schema: Dict, output_path: Path):
    """Generate a Python file with Protocol interfaces."""
    pairs = find_query_pairs(schema)

    lines = [
        '"""',
        'Auto-generated Protocol interfaces for query implementations.',
        '',
        'DO NOT EDIT THIS FILE MANUALLY.',
        'Generated from def/queries.yaml by utils/generate_query_interfaces.py',
        '"""',
        '',
        'from typing import Protocol',
        'from gen.queries import (',
    ]

    # Import all Input and Output classes
    for input_class, output_class in pairs:
        lines.append(f'    {input_class},')
        lines.append(f'    {output_class},')

    lines.append(')')
    lines.append('')
    lines.append('')

    # Generate Protocol for each query pair
    for input_class, output_class in pairs:
        protocol_name = f'{output_class}Protocol'
        lines.append(f'class {protocol_name}(Protocol):')
        lines.append(f'    """Protocol for {output_class} query implementations."""')
        lines.append(f'    ')
        lines.append(f'    def execute(self, query_input: {input_class}) -> {output_class}:')
        lines.append(f'        """Execute the {output_class} query."""')
        lines.append(f'        ...')
        lines.append('')
        lines.append('')

    # Write to file
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w') as f:
        f.write('\n'.join(lines))

    print(f"Generated protocol interfaces: {output_path}")
    print(f"Found {len(pairs)} query pairs:")
    for input_class, output_class in pairs:
        print(f"  - {input_class} -> {output_class}")


def main():
    project_root = Path(__file__).parent.parent
    queries_yaml = project_root / 'def' / 'queries.yaml'
    output_file = project_root / 'queries' / 'interfaces.py'

    schema = parse_queries_yaml(queries_yaml)
    generate_protocol_file(schema, output_file)


if __name__ == '__main__':
    main()
